# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7627b7d62d9145ecbf5ca9d8256802ec66c6dc2eef261f345d40c67971f59fc6c0b16fdc0f423304926de7bdfb59eed5c0c09b6a696682ba3e341f943ff449d2

test:
  secret_key_base: 11999db5073333e4666a4625c079c3e7340a45eca85be00c5cdb1b65dd0f9d0fea37dbe03f1b0bc4a5e852f7c0fcf33d733029a199356daac93794ed4bb8922f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
